
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "@prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "./prisma/migrations",
  },
  // محرك البحث (Engine) يفضل تركه افتراضياً أو استخدام 'library' لـ Vercel

  datasource: {
    url: env("DATABASE_URL"),
    // إذا كنت تستخدم Supabase، أضف السطر التالي:
    // directUrl: env("DIRECT_URL"), 
  },
});